### ISSUE TITLE
How use vue2-storage with typescript

### ISSUE THREAD

**Issue by orifdjon** [yarkovaleksei/vue2-storage#28]
I can't use this library with typescript, because I can't find index.d.ts files for typescript after install through npm

**Comment by orifdjon** [comment]
I found your types in repo and add types in my project, but I caught warning
![2019-05-11_17-36-08](https://user-images.githubusercontent.com/24553301/57571190-676e6700-7413-11e9-9a82-cc4e1ee7d25f.png)

**Comment by yarkovaleksei** [comment]
@orifdjon I fixed it :smiley: Please upgrade package to latest version.

**Comment by orifdjon** [comment]
@yarkovaleksei Thanks a lot))
