### ISSUE TITLE
Disable TTL?

### ISSUE THREAD

**Issue by cdekok** [yarkovaleksei/vue2-storage#32]
Is there an option to keep the storage indefinitely?

**Comment by yarkovaleksei** [comment]
@cdekok Not now, but I will do shortly. Within 2-3 days.

**Comment by SatanZS** [comment]
you can set it to 9999 years😂😂😂

**Comment by yarkovaleksei** [comment]
@cdekok  you can set it to `Infinity`

**Comment by cdekok** [comment]
Is this already pushed? I couldn't find Infinity in the source and the last commit on master is from June 4

**Comment by yarkovaleksei** [comment]
@cdekok No, but this is worked.
See example:

```javascript
Vue.use(Vue2Storage, {
  prefix: 'app_',
  driver: 'local',
  ttl: Infinity
})
```

**Comment by cdekok** [comment]
Ah thanks for the info 👍

**Comment by TerraTech** [comment]
Sorry to necro this, but using ```Infinity``` won't work as ```toJSON()``` will stringify that to ```null```.  When you go to ```get()``` the value, it passes through ```fromJSON()``` where it is parsed back as ```data.ttl = null``` and fails the TTL date check of and immediately removes the key/data:
```javascript
Number(data.ttl) < Date.now()
```
This occurs when you don't explicitly set a ```ttl``` during ```set()``` and rely on the instance default of ```Infinity```

Best advice is set the instance default to a large number of years: e.g. 9999 years
and/or
Explicitly set the ```ttl``` on every ```set()```

A possible P.R. would be to add a test for ```if (data.ttl === null) { data.ttl = this.options.ttl; }``` in ```fromJSON()```.

**Comment by yarkovaleksei** [comment]
@cdekok, @TerraTech Done in version 5.0.0!
