### ISSUE TITLE
remember method type is set to return void

### ISSUE THREAD

**Issue by dorklein** [yarkovaleksei/vue2-storage#47]
### vue & vue2-storage version
2.0.x, x.y.z with typescript

### What is Expected?
`remember (key: string, closure: () => Promise<any>, options?: SetterOptions): Promise<any>;`
or
`remember (key: string, closure: () => Promise<T>, options?: SetterOptions): Promise<T>;`

### What is actually happening?
The remember method type is set to void but in the docs, it returns the value.
`remember (key: string, closure: () => Promise<any>, options?: SetterOptions): void;`

**Comment by Nizari** [comment]
Will this be fixed any time soon?

**Comment by navmed** [comment]
I ran into this too.
