### ISSUE TITLE
Cannot initialize 2 storages at the same time - missing exports

### ISSUE THREAD

**Issue by simahawk** [yarkovaleksei/vue2-storage#49]
### vue & vue2-storage version
2.6.11, 5.0.0

### Steps to reproduce

Try to import the base class instead of the whole plugin and initialize more than one storage.

### What is Expected?

I should be able to import the storage class and initialize extra storage instead of being forced to use only the one added on the root by the plugin installer.

### What is actually happening?

Apparently you can't do that.

FTR I've posted a question here https://stackoverflow.com/questions/61934431/how-to-use-two-different-types-of-storage-at-the-same-time to see if anyone managed to do this w/out hacks but I got no answer.

**Comment by yarkovaleksei** [comment]
Hi @simahawk ! Updated the package to version 6.0.0.

**Comment by simahawk** [comment]
Great, thanks!
